/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bit3_jsass_adapter_NativeTestAdapter */

#ifndef _Included_io_bit3_jsass_adapter_NativeTestAdapter
#define _Included_io_bit3_jsass_adapter_NativeTestAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassPositiveNumberToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassPositiveNumberToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassNegativeNumberToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassNegativeNumberToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassZeroNumberToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassZeroNumberToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassPositiveNumberWithUnitToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassPositiveNumberWithUnitToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassNegativeNumberWithUnitToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassNegativeNumberWithUnitToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassZeroNumberWithUnitToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassZeroNumberWithUnitToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassStringToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassStringToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassQuotedStringToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassQuotedStringToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassTrueToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassTrueToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassFalseToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassFalseToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassRgbColorToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassRgbColorToJava
  (JNIEnv *, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeTestAdapter
 * Method:    testSassRgbaColorToJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeTestAdapter_testSassRgbaColorToJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
