kind: pipeline
name: test-arm

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: eclipse-temurin:11
    failure: ignore
    commands:
      - mkdir -p /tmp/gradle /tmp/gradle_home /tmp/gradle_build
      - ./gradlew --info --full-stacktrace --project-cache-dir /tmp/gradle --gradle-user-home "/tmp/.gradle_home" -Dorg.gradle.project.buildDir=/tmp/gradle_build clean check

---

kind: pipeline
name: test-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: eclipse-temurin:11
    commands:
      - mkdir -p /tmp/gradle /tmp/gradle_home /tmp/gradle_build
      - ./gradlew --info --full-stacktrace --project-cache-dir /tmp/gradle --gradle-user-home "/tmp/.gradle_home" -Dorg.gradle.project.buildDir=/tmp/gradle_build clean check
