/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bit3_jsass_adapter_NativeAdapter */

#ifndef _Included_io_bit3_jsass_adapter_NativeAdapter
#define _Included_io_bit3_jsass_adapter_NativeAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bit3_jsass_adapter_NativeAdapter
 * Method:    compileFile
 * Signature: (Lio/bit3/jsass/adapter/NativeFileContext;)Lio/bit3/jsass/Output;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeAdapter_compileFile
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeAdapter
 * Method:    compileString
 * Signature: (Lio/bit3/jsass/adapter/NativeStringContext;)Lio/bit3/jsass/Output;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_adapter_NativeAdapter_compileString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_bit3_jsass_adapter_NativeAdapter
 * Method:    sass2scss
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_bit3_jsass_adapter_NativeAdapter_sass2scss
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     io_bit3_jsass_adapter_NativeAdapter
 * Method:    libsassVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_bit3_jsass_adapter_NativeAdapter_libsassVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
