/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bit3_jsass_NativeAdapter */

#ifndef _Included_io_bit3_jsass_NativeAdapter
#define _Included_io_bit3_jsass_NativeAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bit3_jsass_NativeAdapter
 * Method:    compileFile
 * Signature: (Lio/bit3/jsass/context/FileContext;)Lio/bit3/jsass/Output;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_NativeAdapter_compileFile
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_bit3_jsass_NativeAdapter
 * Method:    compileString
 * Signature: (Lio/bit3/jsass/context/StringContext;)Lio/bit3/jsass/Output;
 */
JNIEXPORT jobject JNICALL Java_io_bit3_jsass_NativeAdapter_compileString
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
